version: '3.8'

services:
  api:
    image: machineinsight-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: machineinsight-api
    ports:
      - "5000:80"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=machineinsight;Username=postgres;Password=postgres

  db:
    image: postgres:16
    container_name: machineinsight-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: machineinsight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
